theme: jekyll-theme-modernist
title: "Craig's Digital Garden"
description: "Welcome to my digital garden, a space for me to learn in public and help others on a similar journey"
show_downloads: false
